# Generated by Django 3.1.3 on 2020-11-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_payment_usercourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
